name: Deploy code

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: https://registry.npmjs.org/
    - name: Import Secrets
      uses: Infisical/secrets-action@v1.0.15
      with:
        method: "oidc"
        env-slug: "dev"
        project-slug: "github-g0zh"
        identity-id: "1ffe6b17-29ef-47ed-a54c-0912bbe40542"
    - name: build
      run: |
        npm i
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{env.NPM}}
